server:
  port : 8080
  servlet:
    context-path : /tmdemo1

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=taskmanagerdemo1DB;encrypt=false
    username: sa
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey : "afba56f4df0a373b5b53e3ee4719ce7601436eadd7e593cf606eafc86c335e83"